# This file intentionally left blank
BOOTLOADER = rp2040

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

BOOTMAGIC_ENABLE = yes

MOUSEKEY_ENABLE = yes

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
NKRO_ENABLE = yes
